spring.application.name=DocDigest
spring.datasource.url=jdbc:mysql://localhost:3306/docdigest
spring.datasource.username=root
spring.datasource.password=saojnu#1

logging.level.org.springframework.security=TRACE

jwt.secret=ThisIsMySuperSecretJwtKeyForHS2562026
jwt.expiration=86400000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true